baseurl = "https://monterrub.io/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = "true"
title = "Jan Monterrubio"
theme = "hamburg"
publishDir = "docs"

[menu]
	[[menu.main]]
		name = "About"
		identifier = "about"
		url = "pages/about"
        weight = 0
	[[menu.main]]
		name = "Resume"
		identifier = "resume"
		url = "pages/resume"
        weight = -10
    [[menu.main]]
        name = "Projects"
        identifer = "projects"
        url = "projects/"
        weight = -20
    [[menu.main]]
        name = "Blog"
        identifer = "blog"
        url = "blog/"
        weight = -30
